### ISSUE TITLE
Feature Request: Full Date Format

### ISSUE THREAD

**Issue by pento** [Nikoro/system_date_time_format#14]
This is a super useful package, thanks for making it!

Beyond the "long" date format, iOS/MacOS have a "full" date format. I think Android and JS have something similar, not sure about Windows, though. 🙂

It'd be great to have access to that pattern, too.

<img src="https://github.com/Nikoro/system_date_time_format/assets/352291/fcb74a0c-dd43-4479-b933-55c905ce7966" width="300">

**Comment by Nikoro** [comment]
Thank you for the feedback and for the feature request.

iOS and macOS full date pattern is already implemented in dev branch.  So it will be in version 1.1.0 for 100%.
Similarly with web.
Unfortunately Android doesn't have full date format.

Currently checking what is possible on Windows

**Comment by pento** [comment]
Thanks for that, @Nikoro!

Looking at the Android docs, it appears that there isn't a `getFullDateFormat()` helper method in the `android.text.format.DateFormat` class, but it can be retrieved with the somewhere more verbose `java.text.DateFormat.getDateInstance(java.text.DateFormat.FULL)` ([ref](https://developer.android.com/reference/java/text/DateFormat#getDateInstance(int))). Does that look like a possibility to you?

**Comment by Nikoro** [comment]
This is brilliant! @pento 
Thanks a lot!
So full date format for Android will be added in the next version 🎉
